version: '3'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.7.1
    ports:
      - "8080:8080"
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlruns
    command: [ "mlflow", "server", "--host", "0.0.0.0", "--port", "8080"]
